version: '3'
services:
  server:
    build:
      context: .
      dockerfile: ServerDockerFile.dockerfile
    ports:
      - "12345:12345/tcp"
  client:
    build:
      context: .
      dockerfile: ClientDockerFile.dockerfile
    depends_on:
      - server
